"""initial schema baseline

Revision ID: 229e9bd18322
Revises: 
Create Date: 2026-08-06 13:52:14.494851

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '229e9bd18322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_triggered_by'), ['triggered_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('alert_group_buckets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_group_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_group_buckets_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_group_buckets_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_group_buckets_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_group_buckets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_service', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_title_regex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_window_sec', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_session_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_session_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_session_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_session_username'), ['username'], unique=False)

    op.create_table('catalog_actions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('require_hitl', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_actions_entity_kind'), ['entity_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_actions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_actions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('celery_task_failure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('args_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kwargs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=False),
    sa.Column('replayed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('celery_task_failure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_celery_task_failure_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_celery_task_failure_task_name'), ['task_name'], unique=False)

    op.create_table('cicdpipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('yaml_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('security_checks_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_policy_rules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('match_roles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_environments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_tools', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_command_prefixes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_regex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_risk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command_policy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_policy_rules_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_policy_rules_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_policy_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('healthalert',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_history',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('import_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('root_cause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_plan_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commands_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('files_to_check_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validation_steps_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_logs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_logs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_remediation_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_execution_logs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timeline_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('incident_postmortems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sections_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_items_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_variant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_postmortems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_postmortems_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_postmortems_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_postmortems_version'), ['version'], unique=False)

    op.create_table('infrageneration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('terraform_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cli_commands_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_estimate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llmproviderconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key_vault_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fallback_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fallback_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_token_budget', sa.Integer(), nullable=False),
    sa.Column('tokens_used_this_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_servers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('args_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('env_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('require_hitl', sa.Boolean(), nullable=False),
    sa.Column('allowlist_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_servers_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mcp_tool_calls',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arguments_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requires_hitl', sa.Boolean(), nullable=False),
    sa.Column('dangerous', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tool_calls_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_calls_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_calls_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_calls_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_tool_calls_tool_name'), ['tool_name'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', name='uq_permissions_resource_action')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_resource'), ['resource'], unique=False)

    op.create_table('roles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_slug'), ['slug'], unique=True)

    op.create_table('templates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_golden_path_keys', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_slug'), ['slug'], unique=True)

    op.create_table('tool_connections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credentials', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('connected_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_scoped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'tool_id', 'account_alias', name='uq_tool_conn_ws_tool_alias')
    )
    with op.batch_alter_table('tool_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_connections_tool_id'), ['tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_connections_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('tools',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('mfa_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('user_agent_permissions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permission_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_name', name='uq_user_agent')
    )
    with op.batch_alter_table('user_agent_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_agent_permissions_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_agent_permissions_user_id'), ['user_id'], unique=False)

    op.create_table('user_context',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_accounts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pinned_accounts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_switched_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_context_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_context_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('usersetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usersetting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usersetting_key'), ['key'], unique=True)

    op.create_table('webhook_delivery',
    sa.Column('delivery_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_delivery_source'), ['source'], unique=False)

    op.create_table('webhookevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cloud_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhookevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhookevent_cloud_event_id'), ['cloud_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhookevent_timestamp'), ['timestamp'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canvas_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_workspaces_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_calls', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('ai_tool_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requires_hitl', sa.Integer(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tool_executions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tool_executions_message_id'), ['message_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_perm')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('template_applications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applied_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_applications_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_applications_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('tool_accounts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instance_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credentials_vault_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('requires_hitl', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_accounts_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_accounts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_accounts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='uq_user_roles_scope')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('access_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tool_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_requests_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_user_id'), ['user_id'], unique=False)

    op.create_table('template_tools',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Integer(), nullable=False),
    sa.Column('config_hints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tool_accounts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_tools_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_tools_tool_id'), ['tool_id'], unique=False)

    op.create_table('tool_connection_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tool_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account_access',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tool_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_user_account_access')
    )
    with op.batch_alter_table('user_account_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_access_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_account_access_user_id'), ['user_id'], unique=False)

    op.create_table('workspace_tools',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tool_accounts.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_tools_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_tools_workspace_id'))

    op.drop_table('workspace_tools')
    with op.batch_alter_table('user_account_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_account_access_account_id'))

    op.drop_table('user_account_access')
    op.drop_table('tool_connection_logs')
    with op.batch_alter_table('template_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_tools_tool_id'))
        batch_op.drop_index(batch_op.f('ix_template_tools_template_id'))

    op.drop_table('template_tools')
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_account_id'))

    op.drop_table('access_requests')
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_user_id'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('tool_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_accounts_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_tool_accounts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tool_accounts_owner_user_id'))

    op.drop_table('tool_accounts')
    with op.batch_alter_table('template_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_applications_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_template_applications_template_id'))

    op.drop_table('template_applications')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('ai_tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tool_executions_message_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tool_executions_conversation_id'))

    op.drop_table('ai_tool_executions')
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workspaces_slug'))

    op.drop_table('workspaces')
    with op.batch_alter_table('webhookevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhookevent_timestamp'))
        batch_op.drop_index(batch_op.f('ix_webhookevent_cloud_event_id'))

    op.drop_table('webhookevent')
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_source'))

    op.drop_table('webhook_delivery')
    with op.batch_alter_table('usersetting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usersetting_key'))

    op.drop_table('usersetting')
    with op.batch_alter_table('user_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_context_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_user_context_tenant_id'))

    op.drop_table('user_context')
    with op.batch_alter_table('user_agent_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_agent_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_agent_permissions_agent_name'))

    op.drop_table('user_agent_permissions')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_tenant_id'))

    op.drop_table('user')
    op.drop_table('tools')
    with op.batch_alter_table('tool_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_connections_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_tool_connections_tool_id'))

    op.drop_table('tool_connections')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_slug'))

    op.drop_table('templates')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_slug'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_resource'))
        batch_op.drop_index(batch_op.f('ix_permissions_action'))

    op.drop_table('permissions')
    op.drop_table('notification')
    with op.batch_alter_table('mcp_tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tool_calls_tool_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_calls_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_calls_status'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_calls_server_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_tool_calls_requested_by'))

    op.drop_table('mcp_tool_calls')
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_name'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_enabled'))

    op.drop_table('mcp_servers')
    op.drop_table('llmproviderconfig')
    op.drop_table('infrageneration')
    with op.batch_alter_table('incident_postmortems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_postmortems_version'))
        batch_op.drop_index(batch_op.f('ix_incident_postmortems_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_incident_postmortems_incident_id'))

    op.drop_table('incident_postmortems')
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_incident_timestamp'))
        batch_op.drop_index(batch_op.f('ix_incident_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_incident_status'))

    op.drop_table('incident')
    op.drop_table('import_history')
    op.drop_table('healthalert')
    with op.batch_alter_table('command_policy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_policy_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_command_policy_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_command_policy_rules_name'))

    op.drop_table('command_policy_rules')
    op.drop_table('cicdpipeline')
    with op.batch_alter_table('celery_task_failure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_celery_task_failure_task_name'))
        batch_op.drop_index(batch_op.f('ix_celery_task_failure_task_id'))

    op.drop_table('celery_task_failure')
    with op.batch_alter_table('catalog_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_actions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_actions_name'))
        batch_op.drop_index(batch_op.f('ix_catalog_actions_entity_kind'))
        batch_op.drop_index(batch_op.f('ix_catalog_actions_action_type'))

    op.drop_table('catalog_actions')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_session_username'))
        batch_op.drop_index(batch_op.f('ix_auth_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_session_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_auth_session_jti'))

    op.drop_table('auth_session')
    op.drop_table('auditlog')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_name'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('alert_group_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_group_buckets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_alert_group_buckets_rule_id'))
        batch_op.drop_index(batch_op.f('ix_alert_group_buckets_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alert_group_buckets_fingerprint'))

    op.drop_table('alert_group_buckets')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_triggered_by'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
